### ISSUE TITLE
bug反馈 ，egg-cos 导致项目无法使用

### ISSUE THREAD

**Issue by nanhupatar** [axolo/egg-cos#1]
```
    const Cos = options?.COS || CosSdk;
                        ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

`?`，这个应该ts才支持，不适用于es6

**Comment by axolo** [comment]
这个是 ES 2020 Optional Chain， Node.js 14.x 开始正式支持，有条件的话可以升级一下，条件不允许的话，可以fork自行修改。

**Comment by nanhupatar** [comment]
> 这个是 ES 2020 Optional Chain， Node.js 14.x 开始正式支持，有条件的话可以升级一下，条件不允许的话，可以fork自行修改。

有点新，如果兼容8+ ，基本就完美了，我copy 了代码运行。您这个库做的不错，您改一下，发个包就行。这里只需要改动一个地方，重新fork merge， publish费不少劲。这个issue可以关了，我只是反馈这个问题

**Comment by axolo** [comment]
> > 这个是 ES 2020 Optional Chain， Node.js 14.x 开始正式支持，有条件的话可以升级一下，条件不允许的话，可以fork自行修改。
> 
> 有点新，如果兼容8+ ，基本就完美了，我copy 了代码运行。您这个库做的不错，您改一下，发个包就行。这里只需要改动一个地方，重新fork merge， publish费不少劲。这个issue可以关了，我只是反馈这个问题

谢谢您的建议。
